name: create github release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "mock build ..."

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # tag_name: v1.1
        files: |
          build\windows\runner\Release
          build/app/outputs/flutter-apk/app-release.apk
          build/macos/Build/Products/Release/demo.tar.bz2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}