name: flutter ci

on:
  schedule:
    - cron: '0 16 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.build-os }}-latest

    strategy:
      matrix:
        platform: [windows, android, macos]
        include:
        - platform: windows
          build-os: windows
          build_target: windows
        - platform: android
          build-os: macos
          build_target: apk
        - platform: macos
          build-os: macos
          build_target: macos
      fail-fast: false

    steps:
    - id: checkout-source-code
      uses: actions/checkout@v2

    - id: setup-flutter-env
      uses: subosito/flutter-action@v1
      with:
        channel: master
    
    - id: enable-flutter-desktop-support
      run: flutter config --enable-${{ matrix.build-os }}-desktop

    - id: build-flutter-app
      run: flutter build ${{ matrix.build_target }}

    - id: upload-android-app
      if: matrix.platform == 'android'
      uses: actions/upload-artifact@v2
      with:
        name: android-app
        path: build/app/outputs/flutter-apk/app-release.apk

    - id: upload-windows-app
      if: matrix.platform == 'windows'
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: build\windows\runner\Release

    - id: tar-mac-app
      if: matrix.platform == 'macos'
      run: cd build/macos/Build/Products/Release && tar -jcvf demo.tar.bz2 demo.app

    - id: upload-macos-app
      if: matrix.platform == 'macos'
      uses: actions/upload-artifact@v2
      with:
        name: macos-app
        path: build/macos/Build/Products/Release/demo.tar.bz2

    - name: slack notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }} :actor ${{ github.actor }} :commit ${{ github.sha }}
        steps: ${{ toJson(steps) }}
      # always / success/ failure / cancelled
      if: always()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download-android-app
      with:
        name: android-app
        path: android-app

    - uses: actions/download-artifact@v2
      id: download-windows-app
      with:
        name: windows-app
        path: windows-app

    - uses: actions/download-artifact@v2
      id: download-macos-app
      with:
        name: macos-app
        path: macos-app

    - uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        tag_name: v1.2
        files: |
          android-app
          windows-app
          macos-app
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      