name: flutter macos release

on:
  workflow_dispatch:

jobs:
  flutter-macoss-release:
    runs-on: macos-latest

    steps:
    - name: checkout source code
      id: checkout-source-code
      uses: actions/checkout@v2
    
    # - name: make error
    #   id: make-error
    #   run: fdafadaf

    # - uses: subosito/flutter-action@v1
    #   with:
    #     channel: master
    
    # - run: flutter config --enable-macos-desktop
    # - run: flutter build macos

    # - run: cd build/macos/Build/Products/Release && tar -jcvf demo.tar.bz2 demo.app

    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: macos
    #     path: build/macos/Build/Products/Release/demo.tar.bz2

    - name: Upload Artifact
      id: upload
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: windows/runner/resources/app_icon.ico

    - uses: actions/download-artifact@v2
      id: download
      with:
        name: output
        path: output.ico

    - name: 'Echo download path'
      id: show-download-path
      run: echo ${{ toJson(steps.download.outputs) }}

    - name: slack notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }} :actor ${{ github.actor }} :commit ${{ github.sha }}
        steps: ${{ toJson(steps) }}
      if: success()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: slack notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }} :actor ${{ github.actor }} :commit ${{ github.sha }}
        steps: ${{ toJson(steps) }}
      if: failure()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    

    # - uses: mxschmitt/action-tmate@v3