name: flutter android release

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  flutter-android-release:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: subosito/flutter-action@v1
      with:
        channel: master
    
    - run: flutter build apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: apk.zip
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Release
      uses: softprops/action-gh-release@v1
      # 如果不是由git tag触发的action, 此step会跳过
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - uses: mxschmitt/action-tmate@v3