name: flutter cache

on:
  workflow_dispatch:

jobs:
  flutter-cache:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          /Users/runner/hostedtoolcache/flutter
          ~/.pub-cache
        key: flutter-cache

    - uses: subosito/flutter-action@v1
      with:
        channel: master