name: flutter ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.build-os }}-latest

    strategy:
      matrix:
        platform: [windows, android, macos]
        include:
        - platform: windows
          build-os: windows
          build_target: windows
        - platform: android
          build-os: macos
          build_target: apk
        - platform: macos
          build-os: macos
          build_target: macos
      fail-fast: false

    steps:
    - id: checkout-source-code
      uses: actions/checkout@v2

    - id: setup-flutter-env
      uses: subosito/flutter-action@v1
      with:
        channel: master
    
    - id: enable-flutter-desktop-support
      run: flutter config --enable-${{ matrix.build-os }}-desktop
    - id: build-flutter-app
      run: flutter build ${{ matrix.build_target }}