name: build windows

on:
  workflow_dispatch:
    inputs:
      msixVersion:
        type: string
        default: 'x.y.z.0'
        description: 'ms-store version, the last number must be 0'
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install yq
        run: choco install yq
        
      - name: modify msixVersion in pubspec.yaml
        run: yq -i '.version = "${{ inputs.msixVersion }}"' pubspec.yaml
        shell: bash
      
      - name: test msixVersion in pubspec.yaml
        run: cat pubspec.yaml
        shell: bash
        
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 
      
      - name: enable flutter desktop support
        run: flutter config --enable-windows-desktop
      
      - run: flutter pub get

      - name: create msix package
        run: cd D:\a\dev\dev && flutter pub run msix:create

      - name: upload app
        uses: actions/upload-artifact@v2
        with:
          name: msix
          path: build\windows\runner\Release\dev.msix
          retention-days: 1
