name: test options

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - test
          - production
        required: true
        
jobs:
  test:
    runs-on: macos-12
    steps:
      - run: echo  The tags are ${{ inputs.tags }} 
