name: test options

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - beta
          - production
        required: true
        
jobs:
  test:
    runs-on: macos-12
    steps:
      - run: echo  The tags are ${{ inputs.environment }}
      - run: echo  build beta
        if: inputs.environment == 'beta'
      - run: echo  build production
        if: inputs.environment == 'production'
      
