name: debug ubuntu env

on:
  pull_request:
    branches: [ ci ]

  workflow_dispatch:

jobs:
  debug-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LOCAL_SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - run: git clone git@github.com:shukaka/sanbao.git
    - run: ls

